# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 12:35
from __future__ import unicode_literals

import animation.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to=animation.models.upload_directory_path)),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('p', 'Published'), ('w', 'Withdrawn')], default='p', max_length=1)),
            ],
        ),
    ]
