# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('secteur', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('p', 'Published'), ('w', 'Withdrawn')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GroupBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('p', 'Published'), ('w', 'Withdrawn')], default='p', max_length=1)),
            ],
        ),
    ]
