# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 16:45
from __future__ import unicode_literals

import animation.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0003_auto_20180116_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='name',
        ),
        migrations.AddField(
            model_name='bus',
            name='ligne',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animation',
            name='picture',
            field=models.FileField(upload_to=animation.models.upload_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['hap'])]),
        ),
    ]
